# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: atlassian/default-image:2

pipelines:
  default:
    - step:
        name: 'Deployment to Production'
        deployment: production
        script:
          - echo "Your deployment to production script goes here..."
          - git remote set-url origin $GIT_REMOTE
          - git config --global user.email $GIT_EMAIL
          - git config --global user.name $GIT_USERNAME
          - git add .
          - git commit -m $BITBUCKET_COMMIT
          - git push
