# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: atlassian/default-image:2

pipelines:
  branches:
    master:
      - step:
          name: 'Deployment to Production'
          deployment: production
          script:
            - echo "Your deployment to production script goes here..."
            - rm bitbucket-pipelines.yml
            - ls -la
            - git remote add release $GIT_REMOTE
            - git config user.email $GIT_EMAIL
            - git config user.name $GIT_USERNAME
            - git add .
            - git commit -m $BITBUCKET_COMMIT
            - git push release
